days03/demo01/blog/urls.py
from django.conf.urls import url

from . import views
app_name = "blog"

urlpatterns = [
    url(r'^index/$',views.index, name="index"),
    url(r'^add_user/$',views.add_user, name="add_user"),
    # url(r'^delete_user/$',views.delete_user, name="delete_user"),
    # url(r'^(\d+)/delete_user/$',views.delete_user, name="delete_user"),
    # url(r'^delete_user/(\d+)/$',views.delete_user, name="delete_user"),
    url(r'^delete_user/(?P<user_id>\d+)/$',views.delete_user, name="delete_user"),
    url(r'^show/(?P<user_id>\d+)/$',views.show, name="show"),
    url(r'^update/(\d+)/$',views.update, name="update"),


    url(r'^login/$',views.login, name="login"),
    url(r'^logout/$',views.logout, name="logout"),
    url(r'^main/(?P<user_id>\d+)/$',views.main, name="main"),
    url(r'^register/$',views.register, name="register"),
    url(r'^(?P<a_id>\d+)/author_info_editor/$',views.author_info_editor, name="author_info_editor"),
    url(r'^(?P<a_id>\d+)/author_info/$',views.author_info, name="author_info"),
    url(r'^author_info_passwd/$',views.author_info_passwd, name="author_info_passwd"),


    url(r'^(?P<a_id>\d+)/article_single/$',views.article_single, name="article_single"),
    url(r'^(?P<a_id>\d+)/article_delete/$',views.article_delete, name="article_delete"),
    url(r"^(\w+)/checkusername/$", views.checkusername, name="checkusername"),


    url(r'^(?P<a_id>\d+)article_update/$',views.article_update, name="article_update"),

    url(r'^article_publish/$',views.article_publish, name="article_publish"),
    url(r'^code/$',views.code, name="code"),
]

days03/demo01/demo01/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from . import views

import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls",namespace="blog")),
    url(r"^$", views.index, name="index"),
    url(r'^ueditor/', include('DjangoUeditor.urls')),

    url(r'^xadmin/', xadmin.site.urls),
]

days03/demo01/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

days03/demo01/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加数据</title>
    {% load static %}
    <!--<link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="{% static 'js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <!--<script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js"></script>-->
    <script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.min.js' %}"></script>
    <!--<script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>-->
    <script src="{% static 'js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <h2>添加数据</h2>
    <!--{% if username %}-->
        <!--欢迎您{{username}}登录我们的系统-->
    <!--{% else %}-->
        <!--请 <a href="/blog/login">登录</a> 系统-->
    <!--{% endif %}-->


    {% for u in users %}
        {% if u.username %}
            欢迎您{{u.username}}登录我们的系统<br>
        {% else %}
            请 <a href="{% url 'blog:login' %}">登录</a> 系统
        {% endif %}
        {{u.id}}======={{u.username}}======={{u.age}}======={{u.birthday}}======={{u.email}}<br>

    {% empty %}
        没有此用户
    {% endfor %}
    <div class="container">
        <div class="row">
            <div class="panel-body">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <td>用户标示</td>
                            <td>用户名称</td>
                            <td>用户昵称</td>
                            <td>用户年龄</td>
                            <td>用户生日</td>
                            <td>用户邮箱</td>
                            <td>操作</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ forloop.counter0 }}</td>
                                <td>{{ user.username }}</td>
                                <td><a href="{% url 'blog:show' user.id %}">{{ user.nickname }}</a></td>
                                <td>{{ user.age }}</td>
                                <td>{{ user.birthday }}</td>
                                <td>{{ user.email }}</td>
                                <td>
                                    <a href="/blog/update/{{user.id}}/">修改</a>
                                    <!--<a onclick="return window.confirm('是否删除')" href="/blog/delete_user/{{user.id}}/">删除</a>-->
                                    <a onclick="return window.confirm('是否删除')" href="{% url 'blog:delete_user' user.id %}">删除</a>
                                </td>
                            </tr>
                        {% empty%}
                         <tr>
                             <td colspan="6">对不起，当前没有用户</td>
                         </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>



</body>
</html>