days03/demo01/blog/urls.py
from django.conf.urls import url

from . import views
app_name = "blog"

urlpatterns = [
    url(r'^index/$',views.index, name="index"),
    url(r'^add_user/$',views.add_user, name="add_user"),
    # url(r'^delete_user/$',views.delete_user, name="delete_user"),
    # url(r'^(\d+)/delete_user/$',views.delete_user, name="delete_user"),
    # url(r'^delete_user/(\d+)/$',views.delete_user, name="delete_user"),
    url(r'^delete_user/(?P<user_id>\d+)/$',views.delete_user, name="delete_user"),
    url(r'^show/(?P<user_id>\d+)/$',views.show, name="show"),
    url(r'^update/(\d+)/$',views.update, name="update"),


    url(r'^login/$',views.login, name="login"),
    url(r'^logout/$',views.logout, name="logout"),
    url(r'^main/(?P<user_id>\d+)/$',views.main, name="main"),
    url(r'^register/$',views.register, name="register"),
    url(r'^(?P<a_id>\d+)/author_info_editor/$',views.author_info_editor, name="author_info_editor"),
    url(r'^(?P<a_id>\d+)/author_info/$',views.author_info, name="author_info"),
    url(r'^author_info_passwd/$',views.author_info_passwd, name="author_info_passwd"),


    url(r'^(?P<a_id>\d+)/article_single/$',views.article_single, name="article_single"),
    url(r'^(?P<a_id>\d+)/article_delete/$',views.article_delete, name="article_delete"),
    url(r"^(\w+)/checkusername/$", views.checkusername, name="checkusername"),


    url(r'^(?P<a_id>\d+)article_update/$',views.article_update, name="article_update"),

    url(r'^article_publish/$',views.article_publish, name="article_publish"),
    url(r'^code/$',views.code, name="code"),
]

days03/demo01/demo01/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from . import views

import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("blog.urls",namespace="blog")),
    url(r"^$", views.index, name="index"),
    url(r'^ueditor/', include('DjangoUeditor.urls')),

    url(r'^xadmin/', xadmin.site.urls),
]

days03/demo01/blog/models.py
from datetime import datetime

from django.db import models

from DjangoUeditor.models import UEditorField

# from  tinymce.models import HTMLField
# Create your models here.

# class UsersManager(models.Manager):
#     def add_user(self,username,password,age,email):
#         return self.create(username=username,password=password,age=age,email=email)


class Users(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True, verbose_name="用户名称")
    password = models.CharField(max_length=255, verbose_name="用户密码")
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    nickname = models.CharField(max_length=255, null=True, blank=True, verbose_name="用户昵称")
    birthday = models.DateTimeField(auto_now_add=True, verbose_name="用户生日")
    email = models.EmailField(max_length=255, verbose_name="用户邮箱")
    # 默认是0 表示男生， 1表示女生
    gender = models.BooleanField(default=0)

    #头像
    # header = models.CharField(max_length=255, null=True,blank=True, verbose_name='用户头像')
    header = models.ImageField(upload_to='static/upload/herder',default='static/upload/3.jpg', verbose_name='用户头像')


    def __str__(self):
        return self.nickname


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, unique=True, verbose_name="标题")
    # content = HTMLField()
    content = UEditorField()
    publishTime = models.DateTimeField(auto_now_add=True, verbose_name="发表时间")
    modifyTime = models.DateField(auto_now=True, verbose_name="修改时间")
    remark=models.CharField(max_length=255,null=True, blank=True,verbose_name="摘要")


    #外键
    author = models.ForeignKey(Users,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

days03/demo01/blog/views.py
from io import BytesIO
import uuid
import logging


from django.shortcuts import render
from django.shortcuts import redirect,reverse
from django.http import HttpResponse,JsonResponse


from . import models
from . import utils
# Create your views here.
from django.conf import settings
from django.core.paginator import Paginator
from .utils import require_login



from django.core.cache import cache
# from django.core.cache import cache

def index(request):
    logger = logging.getLogger("django")
    logger.warning("首页开始运行了……")
    articles = utils.getAllArticle().order_by('-publishTime')
    # 第一种分页的实现，我们自己手写实现
    pageSize = int(request.GET.get("pageSize", settings.PAGE_SIZE))
    pageNow = int(request.GET.get("pageNow", 1))

    paginator = Paginator(articles, pageSize)
    page = paginator.page(pageNow)
    return render(request, "blog/index.html", {"page": page, "pageSize": pageSize, "pageNow":pageNow})


def add_user(request):
    logger = logging.getLogger("django")
    logger.warning("用户添加")
    users = models.Users.objects.all()
    return render(request,"blog/add_user.html",{"users":users})


def show(request,user_id):
    logger = logging.getLogger("django")
    logger.warning("用户展示")
    users = models.Users.objects.get(pk=user_id)
    return render(request, "blog/show.html", {"users": users})


def update(request,u_id):
    logger = logging.getLogger("django")
    logger.warning("更新数据")
    if request.method=="GET":
        users=models.Users.objects.filter(id=u_id).first()
        return render(request, "blog/update.html", {"users": users})
    else:
        nickname = request.POST["nickname"].strip()
        age = request.POST["age"]
        if int(age)<0:
            return render(request, "blog/update.html", {"msg": "年龄不能小于0"})
        if len(nickname)<1:
            return render(request, "blog/update.html", {"msg": "呢称不能为空"})
        user= models.Users.objects.get(pk=u_id)
        user.age=age
        user.nickname=nickname
        user.save()
        # return redirect("/blog/show/"+ str(u_id)+ "/")
        return redirect(reverse("blog:show",args=(u_id,)))


def delete_user(request,user_id):
    logger = logging.getLogger("django")
    logger.warning("删除用户")
    # users = models.Users.objects.all()
    # u_id = request.GET["id"]
    try:
        user = models.Users.objects.get(pk=user_id)

        user.delete()
        # return render(request, "blog/add_user.html", {"users": users})
        # try:
        return redirect(reverse("blog:add_user"))
    except Exception as e:
        print(e)
        return redirect(reverse("blog:add_user"))
    # except Exception as e :
    #     print(e)
    #     print("#########")
    #     users = models.Users.objects.all()
    #     return render(request, "blog/add_user.html", {"users": users})


def login(request):
    logger = logging.getLogger("django")
    logger.warning("用户登录")
    if request.method == "GET":
        request.session["s1"] = 0
        return render(request,"blog/login.html",{"msg": "请认真填写"})
    elif request.method == "POST":
        username = request.POST.get("username").strip()
        password = request.POST.get("password").strip()
        password1 = request.POST.get("password1").strip()
        res=request.POST.get("res")
        mycode = request.POST.get("code",None)
        save_code=request.session["code"]

        try:
            if request.session["s1"] >= 3:
                if mycode == None or save_code.upper() != mycode.upper():
                    return render(request, "blog/login.html", {"msg": "验证码错误,请正确填写"})
                if password!=password1:
                    request.session["s1"] += 1
                    return render(request, "blog/login.html", {"msg": "两次密码不一致"})
                password=utils.hmac_by_md5(password)
                users=models.Users.objects.get(username=username,password=password)
                request.session["loginUser"] = users
                request.session["s1"] = 0
                if res:
                    response=redirect(reverse("blog:index"))
                    response.set_cookie("password",password)
                    return response
                else:
                    logger = logging.getLogger("django")
                    logger.warning("登录成功…")
                    return redirect(reverse("blog:index"))
            else:
                if password!=password1:
                    request.session["s1"] += 1
                    return render(request, "blog/login.html", {"msg": "两次密码不一致"})
                password = utils.hmac_by_md5(password)
                users=models.Users.objects.get(username=username,password=password)
                request.session["loginUser"] = users
                request.session["s1"] = 0
                if res:
                    response=redirect(reverse("blog:index"))
                    response.set_cookie("password",password)
                    return response
                else:
                    logger = logging.getLogger("django")
                    logger.warning("登录成功…")
                    return redirect(reverse("blog:index"))
        except Exception as e:
            print(e)
            logger = logging.getLogger("django")
            logger.warning("登录失败…")
            request.session["s1"] += 1
            return render(request, "blog/login.html", {"msg": "登陆失败"})


def logout(request):
    logger = logging.getLogger("django")
    logger.warning("退出登录")
    try:
        del request.session["loginUser"]
    finally:
        return redirect(reverse("blog:index"))


@require_login
def main(request,user_id):
    logger = logging.getLogger("django")
    logger.warning("个人主页展示…")
    users = models.Users.objects.get(pk=user_id)
    article=utils.getMyArticle(user_id).order_by('-publishTime')
    # simplejson.loads(serializers.serialize('json', [user])[1:-1])

    pageSize = int(request.GET.get("pageSize", settings.PAGE_SIZE))
    pageNow = int(request.GET.get("pageNow", 1))

    paginator = Paginator(article, pageSize)
    page = paginator.page(pageNow)
    return render(request, "blog/main.html", {"article": page, "pageSize": pageSize, "pageNow": pageNow,"users": users,})

    # return render(request,"blog/main.html",{"users": users,"article":article})


def register(request):
    logger = logging.getLogger("django")
    logger.warning("用户注册…")
    if request.method=="GET":
        return render(request,"blog/register.html",{"msg": "请认真填写"})
    elif request.method=="POST":
        try:
            users = models.Users.objects.all()
            username=request.POST.get("username").strip()
            password = request.POST.get("password").strip()
            password1 = request.POST.get("password1").strip()
            nickname = request.POST.get("nickname").strip()

            mycode = request.POST.get("code", None)
            save_code = request.session["code"]

            if mycode == None or save_code.upper() != mycode.upper():
                del request.session['code']
                return render(request, "blog/login.html", {"msg": "验证码错误,请正确填写"})

            for u in users:
                if username == u.username:
                    return render(request, "blog/register.html", {"msg": "账号不能重复"})
            if len(username)<1:
                return render(request, "blog/register.html", {"msg": "账号不能为空"})
            if len(password)<6:
                return render(request, "blog/register.html", {"msg": "密码长度不能小于六位"})
            if password!=password1:
                return render(request, "blog/register.html", {"msg": "两次密码不一致"})
            password = utils.hmac_by_md5(password)
            user=models.Users(username=username,password=password,nickname=nickname)
            user.save()
            del request.session['code']
            logger = logging.getLogger("django")
            logger.warning("注册成功…")
            return render(request, "blog/register.html", {"msg": "注册成功,请返回登陆"})
        except Exception as e:
            print(e)
            logger = logging.getLogger("django")
            logger.warning("注册失败…")
            return render(request,"blog/register.html",{"msg":"对不起，用户名不能为空"})




def author_info_editor(request,a_id):
    logger = logging.getLogger("django")
    logger.warning("修改个人信息…")
    user = models.Users.objects.get(pk=a_id)
    if request.method == "GET":
        return render(request,"blog/author_info_editor.html",{"users": user})
    else:
        header_img = request.FILES.get("header_img",None)
        # path = 'static/upload/' +uuid.uuid4().hex+ header_img.name
        # try:
        #     with open(path, "wb") as file:
        #         for f in header_img.chunks():
        #             file.write(f)
        #
        # except Exception as e:
        #     print(e)
        #     return redirect(reverse("blog:index"))

        user.header = header_img
        user.save()
        # return redirect(reverse("blog:article_info", kwargs={"a_id": a_id}))
        return redirect(reverse("blog:author_info", kwargs={"a_id": a_id}))



def author_info_passwd(request):
    logger = logging.getLogger("django")
    logger.warning("修改登录密码…")
    if request.method=="GET":
        return render(request, "blog/author_info_passwd.html", {"msg": "请认真填写"})
    else:
        password = request.POST["password"].strip()
        username = request.POST["username"].strip()
        password1 = request.POST["password1"].strip()
        password2 = request.POST["password2"].strip()
        try:
            if password1!=password2:
                return render(request, "blog/author_info_passwd.html", {"msg": "两次输入的密码不一致"})
            password = utils.hmac_by_md5(password)
            users = models.Users.objects.get(username=username, password=password)
            password1 = utils.hmac_by_md5(password1)
            users.password=password1
            users.save()
            logger = logging.getLogger("django")
            logger.warning("修改登录密码成功…")

days03/demo01/blog/templates/blog/article_single.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看单篇文章</title>
    <link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js"></script>
    <script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/static/css/index.css">
    <link rel="stylesheet" href="/static/css/singless.css">
</head>
<body>
<!--网页头部导航条-->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:index' %}">P站</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'blog:index' %}"><i class="glyphicon glyphicon-home"></i> 首页 <span class="sr-only">(current)</span></a></li>
                {% if request.session.loginUser %}
                <li><a href="{% url 'blog:main' request.session.loginUser.id %}"><i class="glyphicon glyphicon-user"></i> 个人主页 </a></li>
                <li><a href="{% url 'blog:article_publish' %}"><i class="glyphicon glyphicon-text-size"></i> 发表文章 </a></li>
                {% endif %}
                <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 我的消息<i class="lable label-danger">10</i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-tag"></i> 网站导航 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'blog:article_publish' %}">发表文章</a></li>
                        <li><a href="#">查看文章</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">查看喜欢的文章</a></li>
                        <li><a href="#">查看收藏的文章</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">查看消息</a></li>
                        <li><a href="#">最新评论</a></li>
                        <li role="separator" class="divider"></li>
                        {% if request.session.loginUser %}
                        <li><a href="{% url 'blog:author_info_passwd' %}">修改登录密码</a></li>
                        <li><a href="{% url 'blog:author_info_editor' request.session.loginUser.id %}">完善个人资料</a></li>
                        {% else %}
                        <li><a href="{% url 'blog:login' %}">登录/注册</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键词">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.loginUser %}
                    <li class="active"><a href="{% url 'blog:author_info' request.session.loginUser.id %}">{{request.session.loginUser.nickname}}</a></li>
                    <li><a href="{% url 'blog:logout' %}">退出登录</a></li>
                {% else %}
                    <li><a href="{% url 'blog:register'%}"><span class="glyphicon glyphicon-tags"></span>
                        新用户注册</a></li>
                    <li><a href="{% url 'blog:login' %}"><span class="glyphicon glyphicon-tags"></span>
                        会员登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!--网页重构-->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-1">
            <div class="row author-info">
                <div class="col-md-12">
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object img-circle" src="/{{article.author.header}}" alt="...">
                            </a>
                        </div>
                        <div class="media-body">
                            <h2 class="media-heading">{{article.author.nickname}}</h2>
                            <ul class="list-inline">
                                <li class="text-center">
                                    <span class="text-muted">{{article.publishTime}}</span>
                                </li>
                                <li class="text-center">
                                    <span class="text-muted">字数 614</span>
                                </li>
                                <li class="text-center">
                                    <span class="text-muted">阅读数 137</span>
                                </li>
                                <li class="text-center">
                                    <span class="text-muted">评论 2</span>
                                </li>
                                <li class="text-center">
                                    <span class="text-muted">喜欢 5</span>
                                </li>
                            </ul>
                        </div>
                        <div class="media-right">
                            {% if article.author.id == request.session.loginUser.id %}
                            <a href="{% url 'blog:article_update' article.id %}"><h5>编辑文章</h5></a>
                            <a onclick="return window.confirm('您确定要删除此文章吗？')" href="{% url 'blog:article_delete' article.id %}"><h5>删除文章</h5></a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="media col-md-8 col-md-offset-2">
                        <h2>{{article.title}}</h2>
                        <p>
                            {{article.content | safe}}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--网页页脚-网站备案信息+友情链接-->
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ul class="list-inline">
                <li><a href="#" class="text-muted">简书</a></li>
                <li><a href="#" class="text-muted">CSDN</a></li>
                <li><a href="#" class="text-muted">百度一下</a></li>
                <li><a href="#" class="text-muted">360搜</a></li>
                <li><a href="#" class="text-muted">搜狐博客</a></li>
                <li><a href="#" class="text-muted">新浪微博</a></li>
                <li><a href="#" class="text-muted">天涯论坛</a></li>
                <li><a href="#" class="text-muted">哔哩哔哩</a></li>
                <li><a href="#" class="text-muted">知乎</a></li>
                <li><a href="#" class="text-muted">啪啦啪啦</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2 text-muted">
            <p>
                版权所有&copy;翻版必究
            </p>
            <p>
                增值电信业务经营许可证B2-20090108　电信与信息服务业务经营许可证000007号
            </p>
            <p>
                广播电视节目制作经营许可证（京）字第828号 甲测资字1100078 京公网安备11000002000016号
            </p>
        </div>
    </div>
</div>
</body>
</html>

days03/demo01/blog/templates/blog/article_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发表文章</title>
    <link rel="stylesheet" href="/static/js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.min.js"></script>
    <script src="/static/js/lib/jquery2.2.4/jquery-2.2.4.js"></script>
    <script src="/static/js/lib/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/static/blog/css/article_publish2.css">


    <link rel="stylesheet" href="/static/ueditor/themes/default/css/ueditor.css">
    <script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>
    <script type="text/javascript" src="/static/ueditor/lang/zh-cn/zh-cn.js"></script>

    <!-- 引入编辑器 依赖文件 -->
    <!--<script src="/static/tiny_mce/tiny_mce.js"></script>-->


    <link rel="stylesheet" href="/static/css/index.css">
</head>
<body>
<!--
    网页头部导航条
 -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:index' %}">P站</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'blog:index' %}"><i class="glyphicon glyphicon-home"></i> 首页 <span class="sr-only">(current)</span></a></li>
                {% if request.session.loginUser %}
                <li><a href="{% url 'blog:main' request.session.loginUser.id %}"><i class="glyphicon glyphicon-user"></i> 个人主页 </a></li>
                <li><a href="{% url 'blog:article_publish' %}"><i class="glyphicon glyphicon-text-size"></i> 发表文章 </a></li>
                {% endif %}
                <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 我的消息<i class="lable label-danger">10</i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-tag"></i> 网站导航 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'blog:article_publish' %}">发表文章</a></li>
                        <li><a href="#">查看文章</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">查看喜欢的文章</a></li>
                        <li><a href="#">查看收藏的文章</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">查看消息</a></li>
                        <li><a href="#">最新评论</a></li>
                        <li role="separator" class="divider"></li>
                        {% if request.session.loginUser %}
                        <li><a href="{% url 'blog:author_info_passwd' %}">修改登录密码</a></li>
                        <li><a href="{% url 'blog:author_info_editor' request.session.loginUser.id %}">完善个人资料</a></li>
                        {% else %}
                        <li><a href="{% url 'blog:login' %}">登录/注册</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入关键词">
                </div>
                <button type="submit" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.loginUser %}
                    <li class="active"><a href="{% url 'blog:author_info' request.session.loginUser.id %}">{{request.session.loginUser.nickname}}</a></li>
                    <li><a href="{% url 'blog:logout' %}">退出登录</a></li>
                {% else %}
                    <li><a href="{% url 'blog:register'%}"><span class="glyphicon glyphicon-tags"></span>
                        新用户注册</a></li>
                    <li><a href="{% url 'blog:login' %}"><span class="glyphicon glyphicon-tags"></span>
                        会员登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<form class="form-horizontal" action="{% url 'blog:article_update' article.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">

        <div style="color:red">
            {{msg}}
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-10 col-md-offset-1">
            <input type="text" class="form-control" name="title" id="title" value="{{article.title}}">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
             <!--文章编辑器：富文本框、markdown编辑器-->
             <!--嵌入一个富文本编辑器-->
            <textarea  name="content" id="content" cols="30" rows="20">
                {{article.content}}
            </textarea>

        </div>
    </div>
    <div class="form-group">
        <div class="col-md-1 col-md-offset-8">
            <button type="submit" class="btn btn-danger">修改文章</button>
        </div>
    </div>
</form>
<!--
    网页页脚- 网站备案信息+友情链接
-->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <ul class="list-inline">
                <li><a href="#" class="text-muted">简书</a></li>
                <li><a href="#" class="text-muted">CSDN</a></li>
                <li><a href="#" class="text-muted">百度一下</a></li>
                <li><a href="#" class="text-muted">360搜</a></li>
                <li><a href="#" class="text-muted">搜狐博客</a></li>
                <li><a href="#" class="text-muted">新浪微博</a></li>
                <li><a href="#" class="text-muted">天涯论坛</a></li>
                <li><a href="#" class="text-muted">哔哩哔哩</a></li>
                <li><a href="#" class="text-muted">知乎</a></li>
                <li><a href="#" class="text-muted">啪啦啪啦</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-muted">
            <p>
                版权所有&copy;翻版必究
            </p>
            <p>
                增值电信业务经营许可证B2-20090108　电信与信息服务业务经营许可证000007号
            </p>
            <p>
                广播电视节目制作经营许可证（京）字第828号 甲测资字1100078 京公网安备11000002000016号
            </p>
        </div>
    </div>
</div>
<script type="text/javascript">
    var content = UE.getEditor('content',{
            'initialFrameWidth': 1300,
            'initialFrameHeight': 500,
            'serverUrl': '/ueditor/controller/?imagePathFormat=&filePathFormat='
        });
    content.ready(function(){

    });
</script>

</body>
</html>

days03/demo01/blog/templates/blog/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示用户信息</title>
</head>
<body>

<div class="container">
        <div class="row">
            <div class="panel-body">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <td colspan="2">用户信息-----{{users.nickname}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>用户账号：</td>
                            <td>{{users.username}}</td>
                        </tr>
                        <tr>
                            <td>用户年龄：</td>
                            <td>{{users.age}}</td>
                        </tr>
                        <tr>
                            <td>用户生日：</td>
                            <td>{{users.birthday}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>